config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'katas#index'

resources :katas
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/belt.rb
class Belt < ApplicationRecord
  belongs_to :kata

  def self.find_kata_id(belt)
    find(belt).kata.id
  end

  def inline()
      "#{name} - #{description}"
  end

end

app/models/kata.rb
class Kata < ApplicationRecord
  validates :title, :description,  presence: true

  has_many :belts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authenticate_admin!
    redirect_to root_path unless admin_signed_in?
  end

private
  def admin_signed_in?
    user_signed_in? && current_user.admin?
  end
end

app/controllers/katas_controller.rb
class KatasController < ApplicationController
  before_action :set_kata, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!,  only: [:new,  :create, :edit, :update, :destroy]

  def index
    @katas = Kata.all
  end

  def show
    @kata = Kata.find(params[:id])
  end

  def new
    @kata = Kata.new
  end

  def create
    @kata = Kata.new(kata_params)

    if @kata.save
      redirect_to kata_path(@kata.id)
    else
      render :new
    end
  end

  def edit
    end

  def update
    @kata.update(kata_params)

    redirect_to kata_path(@kata.id)
  end

  def destroy
    @kata.destroy

    redirect_to root_path
  end

  private
  def set_kata
    @kata = Kata.find(params[:id])
  end

  def kata_params
    params.require(:kata).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def admin_signed_in?
    user_signed_in? && current_user.admin?
  end

end

app/helpers/katas_helper.rb
module KatasHelper
  NO_LINK =''

  def edit_kata_link(id)
    link = link_to('- Edit Kata', edit_kata_path(id))
    return link if admin_signed_in?

    NO_LINK
  end

  def delete_kata_link(id)
    return link_to('- Delete', kata_path(id),
      {method: :delete, data: {confirm: "are you sure?"} } )
    NO_LINK
  end
end

app/views/katas/_form.html.erb
<p>
  <% if @kata.errors  %>
    <ul>
      <% @kata.errors.each do |error| %>
        <li> <%= error %> </li>
      <% end %>
    </ul>
  <% end %>
</p>
<%= form_for(@kata) do |f|%>
  <%= f.text_field :title%>
  <%= f.text_field :description%>
  <%= f.submit t(:save)%>
<%end%>

app/views/katas/edit.html.erb
<center><h1><%= t(:edit) %> </h1></center>

<%= render  'form', note: @kata %>

app/views/katas/index.html.erb
<center><h1>Katas</h1></center>

<%= link_to('Log out', destroy_user_session_path, {method: :delete}) %>


<ul>
<% @katas.each do |kata| %>
  <li>
    <%= link_to(kata.title, kata_path(kata.id)) %>
  - <%= edit_kata_link(kata.id) %>
  - <%= delete_kata_link(kata.id) %>
  </li>

  <% end %>
</ul>


<p>
  <%= link_to('New Kata', new_kata_path) %>
</p>

app/views/katas/new.html.erb
<center><h1>New Kata</h1></center>

<%= render  'form', note: @kata %>

app/views/katas/show.html.erb
<center><%= @kata.title %></center>
<p>
<%= @kata.description %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% I18n.locale = :es %>   
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>